// Classes and structures being serialized

// Generated by ProtocolBuffer
// - a pure c# code generation implementation of protocol buffers
// Report bugs to: https://silentorbit.com/protobuf/

// DO NOT EDIT
// This file will be overwritten when CodeGenerator is run.
// To make custom modifications, edit the .proto file and add //:external before the message line
// then write the code and the changes in a separate file.
using System;
using System.Collections.Generic;

namespace Example
{
    public partial class KVMessage
    {
        public uint Id { get; set; }
        
        public uint Len { get; set; }
        
        public Example.KVRequest Request { get; set; }
        
        public Example.KVResponse Response { get; set; }
        
        // ProtocolBuffers wire field id
        public const int IdFieldID = 1;
        public const int LenFieldID = 2;
        public const int RequestFieldID = 3;
        public const int ResponseFieldID = 4;
    }
    
    public partial class KVResponse
    {
        public uint Status { get; set; }
        
        public string Message { get; set; }
        
        // ProtocolBuffers wire field id
        public const int StatusFieldID = 1;
        public const int MessageFieldID = 2;
    }
    
    public partial class KVRequest
    {
        public enum RequestType
        {
            ITEM = 0,
            LOGIN = 1,
        }
        
        public Example.KVRequest.RequestType Type { get; set; }
        
        public Example.KVItem Item { get; set; }
        
        public Example.KVLogin Login { get; set; }
        
        // ProtocolBuffers wire field id
        public const int TypeFieldID = 1;
        public const int ItemFieldID = 2;
        public const int LoginFieldID = 3;
    }
    
    public partial class KVItem
    {
        public string Command { get; set; }
        
        // ProtocolBuffers wire field id
        public const int CommandFieldID = 1;
    }
    
    public partial class KVLogin
    {
        public string Username { get; set; }
        
        public string Password { get; set; }
        
        // ProtocolBuffers wire field id
        public const int UsernameFieldID = 1;
        public const int PasswordFieldID = 2;
    }
    
}
